#!/bin/bash

# Gasless Coin Creation - Integration Test Guide
# This guide walks through testing the complete gasless system

echo "======================================================================"
echo "🧪 GASLESS COIN CREATION - INTEGRATION TEST"
echo "======================================================================"
echo ""
echo "This test verifies the complete flow:"
echo "  1. User authentication (Privy)"
echo "  2. Smart account creation"
echo "  3. Pimlico paymaster initialization"
echo "  4. Gasless coin deployment"
echo "  5. Zero gas cost verification"
echo ""

# Check environment
echo "✓ Checking environment..."
if grep -q "VITE_PIMLICO_API_KEY" .env; then
  echo "  ✓ VITE_PIMLICO_API_KEY found in .env"
  API_KEY=$(grep "VITE_PIMLICO_API_KEY" .env | cut -d'"' -f2)
  echo "  ✓ API Key: ${API_KEY:0:20}..."
else
  echo "  ❌ VITE_PIMLICO_API_KEY not found in .env"
  exit 1
fi

if grep -q "VITE_PRIVY_APP_ID" .env; then
  echo "  ✓ VITE_PRIVY_APP_ID found in .env"
else
  echo "  ❌ VITE_PRIVY_APP_ID not found in .env"
  exit 1
fi

echo ""
echo "======================================================================"
echo "📋 TEST CHECKLIST"
echo "======================================================================"
echo ""
echo "PHASE 1: Setup & Build (You - Run Now)"
echo "  [ ] npm install"
echo "  [ ] npm run build"
echo ""
echo "PHASE 2: Start Development Server (You - In Terminal)"
echo "  [ ] npm run dev"
echo "  [ ] Wait for: \"VITE v... ready in ... ms\""
echo "  [ ] Application should load at http://localhost:5173"
echo ""
echo "PHASE 3: Browser Testing (You - In Browser)"
echo "  [ ] Open http://localhost:5173"
echo "  [ ] Sign in with test account (or create new)"
echo "  [ ] Check browser console for:"
echo "      ✓ \"💸 Using GASLESS deployment\""
echo "      ✓ \"Smart wallet address: 0x...\""
echo "      ✓ \"Gas fees will be sponsored by Base Paymaster (FREE)\""
echo ""
echo "PHASE 4: Create Test Coin (You - In Browser)"
echo "  [ ] Go to coin creation page"
echo "  [ ] Fill in coin details:"
echo "      Name: \"Test Coin $(date +%s)\""
echo "      Symbol: \"TST$(date +%s | tail -c 3)\""
echo "  [ ] Watch console for success:"
echo "      ✓ \"Transaction sent! Hash: 0x...\""
echo "      ✓ \"Coin deployed at: 0x...\""
echo ""
echo "PHASE 5: Verify on Blockchain Explorer (You - Browser)"
echo "  [ ] Check on Basescan Sepolia:"
echo "      URL: https://sepolia.basescan.org/tx/{transaction_hash}"
echo "  [ ] Verify:"
echo "      ✓ Status: Success"
echo "      ✓ From: Your smart account address"
echo "      ✓ To: Zora Factory (0x777...)"
echo "      ✓ Gas Used: Normal amount"
echo "      ✓ Tx Fee: Shows amount"
echo "  [ ] Critical Check:"
echo "      ✓ Your wallet balance: UNCHANGED (gas was sponsored!)"
echo ""
echo "PHASE 6: Pimlico Dashboard Verification (You - Browser)"
echo "  [ ] Go to https://dashboard.pimlico.io/"
echo "  [ ] Login with Pimlico account"
echo "  [ ] Check:"
echo "      ✓ Operations tab → Recent UOs should show transaction"
echo "      ✓ Status: \"Success\" or \"Pending\""
echo "      ✓ Gas cost should be deducted from credits (not user wallet)"
echo ""
echo "======================================================================"
echo "📊 VERIFICATION CHECKLIST"
echo "======================================================================"
echo ""
echo "✓ Code Level Checks:"
echo "  [x] SmartAccountContext initializes Pimlico paymaster"
echo "  [x] Gasless deployment uses smart account client"
echo "  [x] ZORA pairing configured correctly"
echo "  [x] Environment variables set"
echo ""
echo "⏳ Runtime Checks (Next Steps):"
echo "  [ ] Pimlico API responds (verified in dashboard)"
echo "  [ ] Zora Factory whitelisted (check dashboard)"
echo "  [ ] User UO sponsored successfully"
echo "  [ ] Gas cost = $0 (user wallet balance unchanged)"
echo "  [ ] Coin appears on blockchain"
echo ""
echo "======================================================================"
echo "🚀 QUICK START"
echo "======================================================================"
echo ""
echo "1. Build:"
echo "   npm run build"
echo ""
echo "2. Start dev server (in another terminal):"
echo "   npm run dev"
echo ""
echo "3. Open browser:"
echo "   http://localhost:5173"
echo ""
echo "4. Test coin creation and check console logs"
echo ""
echo "5. Verify transaction:"
echo "   https://sepolia.basescan.org/"
echo ""
echo "6. Check Pimlico dashboard:"
echo "   https://dashboard.pimlico.io/"
echo ""
echo "======================================================================"
echo "❓ TROUBLESHOOTING"
echo "======================================================================"
echo ""
echo "Issue: \"Gas fees will NOT be sponsored\""
echo "Fix: Check that Zora Factory is whitelisted in Pimlico dashboard"
echo ""
echo "Issue: \"Failed to fetch paymaster data\""
echo "Fix: Verify Pimlico API key is correct and has credits"
echo ""
echo "Issue: \"Transaction failed with error\""
echo "Fix: Check browser console for full error message"
echo ""
echo "Issue: \"Wallet balance was deducted\""
echo "Fix: Paymaster not configured correctly - check dashboard"
echo ""
echo "======================================================================"
echo ""
